version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: project-new-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: project-new-db
    volumes:
      - mongo_data:/data/db

  backend:
    image: syedafnan9148/project-new-backend:latest
    container_name: project-new-backend
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongo:27017/project-new-db
      PORT: 3000
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  frontend:
    image: syedafnan9148/project-new-frontend:latest
    container_name: project-new-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4200:4200"

volumes:
  mongo_data:
