version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mean-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: deepikaashok/mean-backend:latest
    container_name: mean-backend
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://mongo:27017/mean-db
      PORT: 3000
    depends_on:
      - mongo
    expose:
      - "3000"   # exposed to other containers only

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: deepikaashok/mean-frontend:latest
    container_name: mean-frontend
    restart: unless-stopped
    depends_on:
      - backend
    expose:
      - "4200"   # exposed to other containers only

  nginx:
    image: nginx:alpine
    container_name: mean-nginx
    restart: unless-stopped
    ports:
      - "80:80"   # exposed externally
    depends_on:
      - frontend
      - backend
    volumes:
